### ISSUE TITLE
Update yellow color on calendar

### ISSUE THREAD

**Issue by whoabuddy** [COVID-19-electronic-health-system/Corona-tracker#542]
### Prerequisites 

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Right now there are two yellow colors in use for the calendar: [#ffff76](https://www.colorhexa.com/ffff76) and [#ffffa9](https://www.colorhexa.com/ffffa9).

```css
.react-calendar__tile--now {
  background-color: #ffff76;
  color: white;
}
.react-calendar__tile--now:enabled:hover,
.react-calendar__tile--now:enabled:focus {
  background-color: #ffffa9;
  color: white;
}
```
Under the right conditions I can select and make a single square yellow of the calendar yellow and the white text is near impossible to read. You can see it in the gif below on the month selection screen as well:

![20200416_115347](https://user-images.githubusercontent.com/9038904/79510861-07088200-7ff3-11ea-965c-116a6a4acc6d.gif)

### Steps to Reproduce

1. Open the calendar screen
2. Select multiple dates, seems to be more common if I "slide" from one day to another
3. Observe the hard to read text

**Expected behavior:**

I expect the text to be legible or a blue color to be used instead.

**Actual behavior:**

The background stays yellow for the active item, and the white text is hard to read.

**Reproduces how often:**

50%

### Additional Information

Idea 1 would be to set the yellow background to always use `color: black` so at least the text is readable when this happens.

Idea 2 would be to replace the yellow with a lighter blue color, but the text may need to be darker in that case as well.
